export enum ServiceNames {
  AUTH_SERVICE = 'AUTH_SERVICE',
  USER_SERVICE = 'USER_SERVICE',
  DOCUMENT_SERVICE = 'DOCUMENT_SERVICE',
  BILLING_SERVICE = 'BILLING_SERVICE',
}

export enum ClientNames {
  AUTH_CLIENT = 'AUTH_CLIENT',
  USER_CLIENT = 'USER_CLIENT',
  DOCUMENT_CLIENT = 'DOCUMENT_CLIENT',
  BILLING_CLIENT = 'BILLING_CLIENT',
}
